"""updated Products and MyProducts table data

Revision ID: 033539e0b32b
Revises: e77cd9d5d3f5
Create Date: 2019-07-17 19:38:28.116111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '033539e0b32b'
down_revision = 'e77cd9d5d3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_products', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('my_products', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('my_products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('my_products', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_my_products_price'), 'my_products', ['price'], unique=False)
    op.create_foreign_key(None, 'my_products', 'type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'my_products', 'supplier', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'my_products', 'department', ['department_id'], ['id'])
    op.drop_index('ix_product_price', table_name='product')
    op.drop_constraint('product_ibfk_3', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_4', 'product', type_='foreignkey')
    op.drop_column('product', 'type_id')
    op.drop_column('product', 'supplier_id')
    op.drop_column('product', 'price')
    op.drop_column('product', 'company_id')
    op.drop_column('product', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('product', sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('product_ibfk_4', 'product', 'company', ['company_id'], ['id'])
    op.create_foreign_key('product_ibfk_2', 'product', 'supplier', ['supplier_id'], ['id'])
    op.create_foreign_key('product_ibfk_1', 'product', 'department', ['department_id'], ['id'])
    op.create_foreign_key('product_ibfk_3', 'product', 'type', ['type_id'], ['id'])
    op.create_index('ix_product_price', 'product', ['price'], unique=False)
    op.drop_constraint(None, 'my_products', type_='foreignkey')
    op.drop_constraint(None, 'my_products', type_='foreignkey')
    op.drop_constraint(None, 'my_products', type_='foreignkey')
    op.drop_index(op.f('ix_my_products_price'), table_name='my_products')
    op.drop_column('my_products', 'type_id')
    op.drop_column('my_products', 'supplier_id')
    op.drop_column('my_products', 'price')
    op.drop_column('my_products', 'department_id')
    # ### end Alembic commands ###
