"""added voters table

Revision ID: 169f1c33e731
Revises: 4ef070c98f17
Create Date: 2019-08-20 22:51:22.597890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '169f1c33e731'
down_revision = '4ef070c98f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('upvotes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_column('post', 'downvote')
    op.drop_column('post', 'upvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('upvote', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('downvote', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('votes')
    op.drop_table('upvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###
