"""added orderslist table

Revision ID: 1e7bdc4ebbd5
Revises: 93094138a220
Create Date: 2019-07-27 22:43:38.894940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7bdc4ebbd5'
down_revision = '93094138a220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_number')
    )
    op.create_index(op.f('ix_orders_list_name'), 'orders_list', ['name'], unique=False)
    op.create_index(op.f('ix_orders_list_price'), 'orders_list', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_list_price'), table_name='orders_list')
    op.drop_index(op.f('ix_orders_list_name'), table_name='orders_list')
    op.drop_table('orders_list')
    # ### end Alembic commands ###
