"""added user profile pic

Revision ID: 2426cf7eeddb
Revises: 6e9b5940fbb0
Create Date: 2019-08-19 19:32:33.593841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2426cf7eeddb'
down_revision = '6e9b5940fbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lot_lot_no', table_name='lot')
    op.create_index(op.f('ix_lot_lot_no'), 'lot', ['lot_no'], unique=True)
    op.add_column('user', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.drop_index(op.f('ix_lot_lot_no'), table_name='lot')
    op.create_index('ix_lot_lot_no', 'lot', ['lot_no'], unique=False)
    # ### end Alembic commands ###
