"""empty message

Revision ID: 27c564b44e5f
Revises: 51d5712f82e5
Create Date: 2019-08-06 16:10:02.559418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27c564b44e5f'
down_revision = '51d5712f82e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_by', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.drop_constraint('purchased_by_ibfk_1', 'purchased_by', type_='foreignkey')
    op.create_foreign_key(None, 'purchased_by', 'purchase', ['purchase_id'], ['id'])
    op.drop_column('purchased_by', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_by', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchased_by', type_='foreignkey')
    op.create_foreign_key('purchased_by_ibfk_1', 'purchased_by', 'order', ['order_id'], ['id'])
    op.drop_column('purchased_by', 'purchase_id')
    # ### end Alembic commands ###
