"""empty message

Revision ID: 2c30fd80bcb5
Revises: 55e8c73f7871
Create Date: 2019-08-25 22:33:16.527821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c30fd80bcb5'
down_revision = '55e8c73f7871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('company_username', table_name='company')
    op.drop_column('company', 'company_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_username', mysql.VARCHAR(collation='utf8_bin', length=128), nullable=True))
    op.create_index('company_username', 'company', ['company_username'], unique=True)
    # ### end Alembic commands ###
