"""empty message

Revision ID: 2dc9ee969a4e
Revises: 65f4126f464f
Create Date: 2019-07-16 23:57:33.514091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dc9ee969a4e'
down_revision = '65f4126f464f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'min_expiry')
    op.drop_column('product', 'min_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('min_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('min_expiry', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
