"""edited order table

Revision ID: 34b4cffa8fa9
Revises: 574f9352e220
Create Date: 2019-07-24 03:55:42.553401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34b4cffa8fa9'
down_revision = '574f9352e220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('create_user', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('order_no', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('review_user', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('submit_user', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_order_no'), 'order', ['order_no'], unique=False)
    op.drop_index('ix_order_order_id', table_name='order')
    op.drop_constraint('order_ibfk_4', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['review_user'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['submit_user'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['create_user'], ['id'])
    op.drop_column('order', 'create_user_id')
    op.drop_column('order', 'submit_user_id')
    op.drop_column('order', 'review_user_id')
    op.drop_column('order', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('order', sa.Column('review_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('submit_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('create_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_2', 'order', 'user', ['review_user_id'], ['id'])
    op.create_foreign_key('order_ibfk_3', 'order', 'user', ['submit_user_id'], ['id'])
    op.create_foreign_key('order_ibfk_4', 'order', 'user', ['create_user_id'], ['id'])
    op.create_index('ix_order_order_id', 'order', ['order_id'], unique=False)
    op.drop_index(op.f('ix_order_order_no'), table_name='order')
    op.drop_column('order', 'submit_user')
    op.drop_column('order', 'review_user')
    op.drop_column('order', 'order_no')
    op.drop_column('order', 'create_user')
    # ### end Alembic commands ###
