"""item table, removed sequence no, added purchase_list_to_item

Revision ID: 377109402250
Revises: 6b6291d4dabc
Create Date: 2019-08-06 15:26:25.014690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '377109402250'
down_revision = '6b6291d4dabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('purchase_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'purchase_list', ['purchase_list_id'], ['id'])
    op.drop_column('item', 'sequence_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sequence_no', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'purchase_list_id')
    # ### end Alembic commands ###
