"""removed completed and reviewed in order table

Revision ID: 3cabcb6ec168
Revises: 6be335ac644b
Create Date: 2019-08-03 11:15:00.511419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cabcb6ec168'
down_revision = '6be335ac644b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_completed_by', table_name='order')
    op.drop_index('ix_order_date_completed', table_name='order')
    op.drop_index('ix_order_review_approved', table_name='order')
    op.drop_constraint('order_ibfk_4', 'order', type_='foreignkey')
    op.drop_column('order', 'reviewer')
    op.drop_column('order', 'review_approved')
    op.drop_column('order', 'date_completed')
    op.drop_column('order', 'completed_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('completed_by', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('date_completed', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('review_approved', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('reviewer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('order_ibfk_4', 'order', 'user', ['reviewer'], ['id'])
    op.create_index('ix_order_review_approved', 'order', ['review_approved'], unique=False)
    op.create_index('ix_order_date_completed', 'order', ['date_completed'], unique=False)
    op.create_index('ix_order_completed_by', 'order', ['completed_by'], unique=False)
    # ### end Alembic commands ###
