"""added purchase and purchaselist table

Revision ID: 413e7c9bcc7b
Revises: a6728dc4eec8
Create Date: 2019-08-04 10:45:49.249720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '413e7c9bcc7b'
down_revision = 'a6728dc4eec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_list_name'), 'purchase_list', ['name'], unique=False)
    op.create_index(op.f('ix_purchase_list_price'), 'purchase_list', ['price'], unique=False)
    op.add_column('delivery', sa.Column('delivery_no', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_delivery_delivery_no'), 'delivery', ['delivery_no'], unique=True)
    op.drop_index('ix_delivery_delivery_id', table_name='delivery')
    op.drop_column('delivery', 'delivery_id')
    op.drop_index('ix_order_order_no', table_name='order')
    op.create_index(op.f('ix_order_order_no'), 'order', ['order_no'], unique=True)
    op.add_column('orders_list', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders_list', 'user', ['user_id'], ['id'])
    op.add_column('purchase', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('purchase', sa.Column('purchase_order_no', sa.String(length=50), nullable=True))
    op.add_column('purchase', sa.Column('purchased_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_date_created'), 'purchase', ['date_created'], unique=False)
    op.create_index(op.f('ix_purchase_purchase_order_no'), 'purchase', ['purchase_order_no'], unique=True)
    op.drop_index('ix_purchase_purchase_id', table_name='purchase')
    op.drop_constraint('purchase_ibfk_3', 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'purchase', 'user', ['purchased_by'], ['id'])
    op.drop_column('purchase', 'purchase_id')
    op.drop_column('purchase', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('purchase_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.create_foreign_key('purchase_ibfk_3', 'purchase', 'user', ['user_id'], ['id'])
    op.create_index('ix_purchase_purchase_id', 'purchase', ['purchase_id'], unique=False)
    op.drop_index(op.f('ix_purchase_purchase_order_no'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_date_created'), table_name='purchase')
    op.drop_column('purchase', 'purchased_by')
    op.drop_column('purchase', 'purchase_order_no')
    op.drop_column('purchase', 'date_created')
    op.drop_column('purchase', 'created_by')
    op.drop_constraint(None, 'orders_list', type_='foreignkey')
    op.drop_column('orders_list', 'user_id')
    op.drop_index(op.f('ix_order_order_no'), table_name='order')
    op.create_index('ix_order_order_no', 'order', ['order_no'], unique=False)
    op.add_column('delivery', sa.Column('delivery_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.create_index('ix_delivery_delivery_id', 'delivery', ['delivery_id'], unique=False)
    op.drop_index(op.f('ix_delivery_delivery_no'), table_name='delivery')
    op.drop_column('delivery', 'delivery_no')
    op.drop_index(op.f('ix_purchase_list_price'), table_name='purchase_list')
    op.drop_index(op.f('ix_purchase_list_name'), table_name='purchase_list')
    op.drop_table('purchase_list')
    # ### end Alembic commands ###
