"""changed purchase order_id to order_no

Revision ID: 41892fa57909
Revises: 413e7c9bcc7b
Create Date: 2019-08-04 12:55:39.574716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41892fa57909'
down_revision = '413e7c9bcc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('order_no', sa.Integer(), nullable=True))
    op.drop_constraint('purchase_ibfk_2', 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'order', ['order_no'], ['order_no'])
    op.drop_column('purchase', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.create_foreign_key('purchase_ibfk_2', 'purchase', 'order', ['order_id'], ['id'])
    op.drop_column('purchase', 'order_no')
    # ### end Alembic commands ###
