"""added one to many purchased by table

Revision ID: 43319083eabb
Revises: 377109402250
Create Date: 2019-08-06 15:51:51.746348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43319083eabb'
down_revision = '377109402250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_by',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchased_by')
    # ### end Alembic commands ###
