"""empty message

Revision ID: 4ad5959906ce
Revises: 41892fa57909
Create Date: 2019-08-04 13:25:40.328774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ad5959906ce'
down_revision = '41892fa57909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'purchase_id')
    op.drop_column('purchase', 'user_id')
    op.drop_column('purchase', 'order_no')
    op.drop_column('purchase', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('order_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('purchase', sa.Column('purchase_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    # ### end Alembic commands ###
