"""changed purchased by table to many to amny

Revision ID: 51d5712f82e5
Revises: 907fe442778f
Create Date: 2019-08-06 15:58:28.584028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51d5712f82e5'
down_revision = '907fe442778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_by',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('purchase_ibfk_6', 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'purchased_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchased_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_ibfk_6', 'purchase', 'user', ['purchased_by_id'], ['id'])
    op.drop_table('purchased_by')
    # ### end Alembic commands ###
