"""added company emal and username

Revision ID: 55e8c73f7871
Revises: 3362011b8442
Create Date: 2019-08-25 21:45:08.869084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e8c73f7871'
down_revision = '3362011b8442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_username', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    op.create_unique_constraint(None, 'company', ['company_username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_column('company', 'email')
    op.drop_column('company', 'company_username')
    # ### end Alembic commands ###
