"""edited order table

Revision ID: 574f9352e220
Revises: 670f99f03e15
Create Date: 2019-07-23 23:37:06.773952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '574f9352e220'
down_revision = '670f99f03e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('create_user_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_submitted', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('review_approved', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('review_user_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('submit_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_date_created'), 'order', ['date_created'], unique=False)
    op.create_index(op.f('ix_order_date_submitted'), 'order', ['date_submitted'], unique=False)
    op.create_index(op.f('ix_order_review_approved'), 'order', ['review_approved'], unique=False)
    op.drop_index('ix_order_date_ordered', table_name='order')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['review_user_id'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['submit_user_id'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['create_user_id'], ['id'])
    op.drop_column('order', 'date_ordered')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('date_ordered', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_2', 'order', 'user', ['user_id'], ['id'])
    op.create_index('ix_order_date_ordered', 'order', ['date_ordered'], unique=False)
    op.drop_index(op.f('ix_order_review_approved'), table_name='order')
    op.drop_index(op.f('ix_order_date_submitted'), table_name='order')
    op.drop_index(op.f('ix_order_date_created'), table_name='order')
    op.drop_column('order', 'submit_user_id')
    op.drop_column('order', 'review_user_id')
    op.drop_column('order', 'review_approved')
    op.drop_column('order', 'date_submitted')
    op.drop_column('order', 'date_created')
    op.drop_column('order', 'create_user_id')
    # ### end Alembic commands ###
