"""removed product code from Product model

Revision ID: 65f4126f464f
Revises: e8ad24a7092f
Create Date: 2019-07-16 23:54:03.288070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65f4126f464f'
down_revision = 'e8ad24a7092f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_name', table_name='product')
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.drop_index('product_code', table_name='product')
    op.drop_column('product', 'product_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_code', mysql.VARCHAR(collation='utf8_bin', length=100), nullable=True))
    op.create_index('product_code', 'product', ['product_code'], unique=True)
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.create_index('ix_product_name', 'product', ['name'], unique=True)
    # ### end Alembic commands ###
