"""created lot item order purchase delivery table

Revision ID: 670f99f03e15
Revises: 033539e0b32b
Create Date: 2019-07-23 19:41:05.647364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '670f99f03e15'
down_revision = '033539e0b32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(length=50), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_expiry'), 'lot', ['expiry'], unique=False)
    op.create_index(op.f('ix_lot_lot_no'), 'lot', ['lot_no'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('date_ordered', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_date_ordered'), 'order', ['date_ordered'], unique=False)
    op.create_index(op.f('ix_order_order_id'), 'order', ['order_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.String(length=50), nullable=True),
    sa.Column('date_purchased', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_date_purchased'), 'purchase', ['date_purchased'], unique=False)
    op.create_index(op.f('ix_purchase_purchase_id'), 'purchase', ['purchase_id'], unique=False)
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=True),
    sa.Column('date_delivered', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_date_delivered'), 'delivery', ['date_delivered'], unique=False)
    op.create_index(op.f('ix_delivery_delivery_id'), 'delivery', ['delivery_id'], unique=False)
    op.drop_index('ix_orders_date_ordered', table_name='orders')
    op.drop_table('orders')
    op.drop_table('orders_list')
    op.add_column('item', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('delivery_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.drop_index('ix_item_expiry', table_name='item')
    op.drop_index('ix_item_lot_no', table_name='item')
    op.create_foreign_key(None, 'item', 'delivery', ['delivery_id'], ['id'])
    op.create_foreign_key(None, 'item', 'company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'item', 'lot', ['lot_id'], ['id'])
    op.drop_column('item', 'lot_no')
    op.drop_column('item', 'expiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('expiry', mysql.DATETIME(), nullable=True))
    op.add_column('item', sa.Column('lot_no', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_index('ix_item_lot_no', 'item', ['lot_no'], unique=False)
    op.create_index('ix_item_expiry', 'item', ['expiry'], unique=False)
    op.drop_column('item', 'lot_id')
    op.drop_column('item', 'delivery_id')
    op.drop_column('item', 'company_id')
    op.create_table('orders_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prod_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], name='orders_list_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_ordered', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='orders_ibfk_2'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='orders_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='orders_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_orders_date_ordered', 'orders', ['date_ordered'], unique=False)
    op.drop_index(op.f('ix_delivery_delivery_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_date_delivered'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_purchase_purchase_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_date_purchased'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_order_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_date_ordered'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_lot_lot_no'), table_name='lot')
    op.drop_index(op.f('ix_lot_expiry'), table_name='lot')
    op.drop_table('lot')
    # ### end Alembic commands ###
