"""empty message

Revision ID: 6b6291d4dabc
Revises: 4ad5959906ce
Create Date: 2019-08-04 14:19:37.197428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6291d4dabc'
down_revision = '4ad5959906ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('order_no', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'order', ['order_no'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'order_no')
    # ### end Alembic commands ###
