"""replaced purchased created by to m2m table

Revision ID: 6e9b5940fbb0
Revises: 27c564b44e5f
Create Date: 2019-08-07 10:14:41.132158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9b5940fbb0'
down_revision = '27c564b44e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_created_by',
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('purchase_ibfk_3', 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('purchase_ibfk_3', 'purchase', 'user', ['created_by'], ['id'])
    op.drop_table('purchase_created_by')
    # ### end Alembic commands ###
