"""added role access to affiliate table

Revision ID: 7de42c610190
Revises: d7d3f930eb0d
Create Date: 2019-07-08 18:50:31.940358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de42c610190'
down_revision = 'd7d3f930eb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('inv_access', sa.Boolean(), nullable=True))
    op.add_column('affiliates', sa.Column('inv_admin', sa.Boolean(), nullable=True))
    op.add_column('affiliates', sa.Column('qc_access', sa.Boolean(), nullable=True))
    op.add_column('affiliates', sa.Column('qc_admin', sa.Boolean(), nullable=True))
    op.add_column('affiliates', sa.Column('super_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliates', 'super_admin')
    op.drop_column('affiliates', 'qc_admin')
    op.drop_column('affiliates', 'qc_access')
    op.drop_column('affiliates', 'inv_admin')
    op.drop_column('affiliates', 'inv_access')
    # ### end Alembic commands ###
