"""empty message

Revision ID: 907fe442778f
Revises: 3bccf578f7f3
Create Date: 2019-08-06 15:56:23.960567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '907fe442778f'
down_revision = '3bccf578f7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchased_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('purchase_ibfk_4', 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'user', ['purchased_by_id'], ['id'])
    op.drop_column('purchase', 'purchased_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('purchased_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.create_foreign_key('purchase_ibfk_4', 'purchase', 'user', ['purchased_by'], ['id'])
    op.drop_column('purchase', 'purchased_by_id')
    # ### end Alembic commands ###
