"""added complete by and date on orders

Revision ID: a5a5d4f26186
Revises: bf8b29061028
Create Date: 2019-07-31 18:10:58.628387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a5d4f26186'
down_revision = 'bf8b29061028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('completed_by', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('date_ompletedd', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_order_completed_by'), 'order', ['completed_by'], unique=False)
    op.create_index(op.f('ix_order_date_ompletedd'), 'order', ['date_ompletedd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_date_ompletedd'), table_name='order')
    op.drop_index(op.f('ix_order_completed_by'), table_name='order')
    op.drop_column('order', 'date_ompletedd')
    op.drop_column('order', 'completed_by')
    # ### end Alembic commands ###
