"""added title role to user affiliate

Revision ID: a86b19755316
Revises: 2426cf7eeddb
Create Date: 2019-08-19 21:21:31.735590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86b19755316'
down_revision = '2426cf7eeddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_affiliates_title'), 'affiliates', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliates_title'), table_name='affiliates')
    op.drop_column('affiliates', 'title')
    # ### end Alembic commands ###
