"""edited order table

Revision ID: bccc236761d0
Revises: 34b4cffa8fa9
Create Date: 2019-07-24 03:58:59.077884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bccc236761d0'
down_revision = '34b4cffa8fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_creator', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('reviewer', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_4', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['submitted_by'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['order_creator'], ['id'])
    op.create_foreign_key(None, 'order', 'user', ['reviewer'], ['id'])
    op.drop_column('order', 'create_user')
    op.drop_column('order', 'submit_user')
    op.drop_column('order', 'review_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('review_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('submit_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('create_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ibfk_2', 'order', 'user', ['review_user'], ['id'])
    op.create_foreign_key('order_ibfk_4', 'order', 'user', ['create_user'], ['id'])
    op.create_foreign_key('order_ibfk_3', 'order', 'user', ['submit_user'], ['id'])
    op.drop_column('order', 'submitted_by')
    op.drop_column('order', 'reviewer')
    op.drop_column('order', 'order_creator')
    # ### end Alembic commands ###
