"""removed unique ref_num from orderslist table

Revision ID: bf8b29061028
Revises: 1e7bdc4ebbd5
Create Date: 2019-07-30 00:39:27.316323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8b29061028'
down_revision = '1e7bdc4ebbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ref_number', table_name='orders_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ref_number', 'orders_list', ['ref_number'], unique=True)
    # ### end Alembic commands ###
