"""added products m2m associatio obj

Revision ID: e77cd9d5d3f5
Revises: 2dc9ee969a4e
Create Date: 2019-07-17 18:31:10.629403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77cd9d5d3f5'
down_revision = '2dc9ee969a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_products',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_expiry', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_products')
    # ### end Alembic commands ###
